services:
  - type: web
    name: your-app-name
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: GOOGLE_API_KEY
        fromService:
          type: secret
          name: google-api-key
      - key: SERPAPI_API_KEY
        fromService:
          type: secret
          name: serpapi-api-key
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: "sqlite:///instance/site.db"
      - key: PYTHONUNBUFFERED
        value: "True"
